# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: TP-Link Switch Prometheus Exporter
version: "1.0.0"
slug: tplink-switch-prometheus-exporter
description: TP-Link Switch Prometheus Exporter for Home Assistant
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  http_port: 8000
  switches:
    - ip: "192.168.1.1"
      username: "admin"
      password: "admin"
      cache_login: True
      http_port: 80
schema:
  http_port: int(0,9999)
  switches:
    - ip: "str"
      username: "str"
      password: "password"
      cache_login: "bool"
      http_port: "int"
